main:
  active_dataset: "water"
  run_preprocess: false
  train_and_predict: true

datasets:
  water:
    target: "status_group"
    id_column: "id"
    problem_type: "classification"
  insurance:
    target: "Premium Amount"
    id_column: "id"
    problem_type: "regression"
  car:
    target: "price"
    id_column: "id"
    problem_type: "regression"

gradient_boosting:
  weak_learner_key: "neural_network"
  n_estimators: 10000
  learning_rate: 0.3
  subsample: 0.8
  colsample_bytree: 0.8
  reg_lambda: 1.0
  early_stopping_rounds: 25

decision_tree:
  max_depth: 4
  random_state: 42

neural_network:
  epochs: 10
  learning_rate: 0.01
  max_norm: 1.0
  hidden_size: 256
  batch_size: 256