main:
  active_dataset: "insurance"
  run_preprocess: false
  train_and_predict: true

datasets:
  water:
    target: "status_group"
    id_column: "id"
    problem_type: "classification"
  insurance:
    target: "Premium Amount"
    id_column: "id"
    problem_type: "regression"

gradient_boosting:
  weak_learner_key: "neural_network"
  n_estimators: 5
  learning_rate: 0.01
  subsample: 0.8
  colsample_bytree: 0.8
  early_stopping_rounds: 20

decision_tree:
  max_depth: 4
  random_state: 42

neural_network:
  epochs: 5
  learning_rate: 0.01
  weight_decay: 0.001
  dropout: 0.1
  hidden_size: 512
  batch_size: 1024