# ==============================================================================
# DATASETS SETTINGS
# ==============================================================================

heart:
  id_column: "id"                     # Unique ID for each row
  target: "Heart Disease"             # Target column name
  problem_type: "classification"      # Classification task
  cat_cols:                           # Categorical feature column names
    - "Sex"
    - "Chest pain type"
    - "FBS over 120"
    - "EKG results"
    - "Exercise angina"
    - "Slope of ST"
    - "Number of vessels fluro"
    - "Thallium"
  num_cols:                           # Continuous feature column names
    - "Age"
    - "BP"
    - "Cholesterol"
    - "Max HR"
    - "ST depression"

scores:
  id_column: "id"                     # Unique ID for each row
  target: "exam_score"                # Target column name
  problem_type: "regression"          # Regression task
  cat_cols:                           # Categorical feature column names
    - "gender"
    - "course"
    - "internet_access"
    - "sleep_quality"
    - "study_method"
    - "facility_rating"
    - "exam_difficulty"
  num_cols:                           # Continuous feature column names
    - "age"
    - "study_hours"
    - "class_attendance"
    - "sleep_hours"

mnist:
  id_column: "id"                     # Unique ID for each image
  target: "Label"                     # Target column name
  problem_type: "computer_vision"     # Computer vision task

cifar10:
  id_column: "id"                     # Unique ID for each image
  target: "label"                     # Target column name
  problem_type: "computer_vision"     # Computer vision task