heart:
  id_column: "id"
  target: "Heart Disease"
  cat_cols:
    - "Sex"
    - "Chest pain type"
    - "FBS over 120"
    - "EKG results"
    - "Exercise angina"
    - "Slope of ST"
    - "Number of vessels fluro"
    - "Thallium"
  num_cols:
    - "Age"
    - "BP"
    - "Cholesterol"
    - "Max HR"
    - "ST depression"
  problem_type: "classification"

scores:
  id_column: "id"
  target: "exam_score"
  cat_cols:
    - "gender"
    - "course"
    - "internet_access"
    - "sleep_quality"
    - "study_method"
    - "facility_rating"
    - "exam_difficulty"
  num_cols:
    - "age"
    - "study_hours"
    - "class_attendance"
    - "sleep_hours"
  problem_type: "regression"

mnist:
  id_column: "id"
  target: "Label"
  problem_type: "computer_vision"

cifar10:
  id_column: "id"
  target: "label"
  problem_type: "computer_vision"