main:
  active_dataset: "cifar10"
  run_preprocess: false
  train_and_predict: true

gradient_boosting:
  weak_learner_key: "convolutional_neural_network"
  n_estimators: 10
  learning_rate: 0.5
  subsample: 1.0
  colsample_bytree: 1.0
  reg_lambda: 0.5
  early_stopping_rounds: 10

decision_tree:
  max_depth: 5

neural_network:
  epochs: 3
  hidden_size: 16
  batch_size: 16

convolutional_neural_network:
  channels: 16
  kernel_size: 5
  pool_size: 2
  hidden_size: 64
  batch_size: 16